# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20160828_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
